### ISSUE TITLE
Nature demo down.

### ISSUE THREAD

**Issue by Carreau** [jupyter/nature-demo#17]
502 gateway error.

Will retry later.

**Comment by rgbkrk** [comment]
Ruh roh! I'm not able to reach into this at the moment. @minrk, are you willing to check this out?

**Comment by minrk** [comment]
I'll see if I can find what's up.

**Comment by minrk** [comment]
Sorry, I failed and have to go now. Hopefully @rgbkrk will have a chance to get it back up.

**Comment by Carreau** [comment]
Still down.

**Comment by rgbkrk** [comment]
More like down again.

We never said we'd run it this long, that's for sure.

**Comment by Carreau** [comment]
Yeah, it just looks weird to see the 502 in the middle of the page. 
We should contact nature and turn it (at least) into a static page.

**Comment by Carreau** [comment]
cc @fperez

**Comment by Carreau** [comment]
Just annoying because Binder is also down and I wanted to make a demo tomorrow.

**Comment by rgbkrk** [comment]
Ah, that's too bad because it's tempting to defer it to binder instead.

The way the nature demo works is that they embed an iframe that points to `nature.tmpnb.org`. We can put a static site there pretty easily. Happy to do that with surge.sh, even it it just redirects to nbviewer.

**Comment by minrk** [comment]
There was some maintenance on IAD, which looks like it rebooted the server. I cleaned out some containers and relaunched things, and it looks to be back up now.

**Comment by rgbkrk** [comment]
Awesome, thanks Min. I wasn't even sure I could reach the server.
